Fixing Promise related compiler errors
We don't expect any content for `ITransport.send` methods so the `.ITransportsend` method just returns `Promise<void>`. However LongPolling and ServerSentEvents transport use the standard HttpClient to send send requests whose return type is `Promise<string>`. This causes:

error TS2322: Type 'Promise<string>' is not assignable to type 'Promise<void>'.